server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shushidemao/springcloud-config.git #github上面的git仓库地址，代表从远程仓库获取配置信息
          search-paths:
            - springcloud-config #代表从哪个仓库获取配置
          skip-ssl-validation: true
      label: master #从哪个分支获取配置

eureka:
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否拉取服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      #单机版
      defaultZone: http://127.0.0.1:7001/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config3344
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳时间间隔，时间单位为秒，默认30s
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端接收服务最后一次心跳后等待时间，单位为秒，默认为90s，超时将删除服务
    #lease-expiration-duration-in-seconds: 2

    ip-address: 127.0.0.1