server:
  port: 8001

spring:
  application:
    name: cloud-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      #单机版
      #defaultZone: http://127.0.0.1:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳时间间隔，时间单位为秒，默认30s
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端接收服务最后一次心跳后等待时间，单位为秒，默认为90s，超时将删除服务
    #lease-expiration-duration-in-seconds: 2

    ip-address: 127.0.0.1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wy.springcloud.entity


