server:
  port: 9527

spring:
  application:
    name: cloud-dateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启拉取注册中心服务列表，动态创建路由，利用微服务名进行路由
      routes: #路由
        # - 的作用：集合类型，可以有多个的(比如以下的id、Path，可以配置多个，则需要加上“-”)
          #id:路由名字，没有固定规则，但是必须唯一
        - id: payment  #路由名字，没有固定规则，但是必须唯一
          #uri：匹配后提供服务的路由地址
          #uri: https://localhost:8001  #固定地址
          #lb:LoadBalance,支持负载均衡
          uri: lb://CLOUD-PROVIDER  #动态路由，取得服务名，对应的8001和8002两个服务地址
          #断言，必选全部符合以下断言的条件
          predicates:
            - Path=/payment/getPort/**  #路径匹配，只要请求路径匹配上了path，就往uri转发，并且将路径带上
            - Method=GET,POST #请求方式匹配，只能GET或者POST请求
          #过滤器：可以在请求被路由前或者后对请求进行修改
          #filters:
            #- AddRequestHeader=X-Request-red, blue  #请添加求头


eureka:
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否拉取服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      #单机版
      defaultZone: http://127.0.0.1:7001/eureka/
      #集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳时间间隔，时间单位为秒，默认30s
    #lease-renewal-interval-in-seconds: 1
    #eureka服务端接收服务最后一次心跳后等待时间，单位为秒，默认为90s，超时将删除服务
    #lease-expiration-duration-in-seconds: 2

    ip-address: 127.0.0.1